#!/bin/bash

cat samples/table-ordered-colored.txt | bin/parse-table -row_order_col -col_order_row -use_row_order_col -use_col_order_row -row_color_col -col_color_row -use_row_color_col -use_col_color_row | bin/make-conf -dir data
../../bin/circos -conf etc/circos.conf -outputfile table-ordered-colored.png

